upstream app {
    server app1:8000 weight=8;
    server app2:8000 weight=5;
    server app3:8000 weight=4;
    server app4:8000 weight=3;
}

server  {
  listen 80;
  location / {
    proxy_pass http://app;
  }
}